apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: sarussiware
# Schema is created by Prisma migrations; no init script needed.
data:
  init.sql: |
    -- (empty; Prisma migrate deploy creates tables)
